object FormMain: TFormMain
  Left = 0
  Top = 0
  Caption = #20182#12398#12450#12503#12522#12408'D&D'
  ClientHeight = 354
  ClientWidth = 257
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 257
    Height = 25
    Align = alTop
    Caption = 'Text'
    TabOrder = 0
  end
  object ListBox1: TListBox
    Left = 0
    Top = 25
    Width = 257
    Height = 40
    Align = alTop
    ItemHeight = 13
    TabOrder = 1
  end
  object Panel2: TPanel
    Left = 0
    Top = 65
    Width = 257
    Height = 25
    Align = alTop
    Caption = 'Html'
    TabOrder = 2
    ExplicitTop = 97
  end
  object ListBox2: TListBox
    Left = 0
    Top = 90
    Width = 257
    Height = 47
    Align = alTop
    ItemHeight = 13
    TabOrder = 3
  end
  object Panel3: TPanel
    Left = 0
    Top = 137
    Width = 257
    Height = 25
    Align = alTop
    Caption = 'File'
    TabOrder = 4
    ExplicitTop = 200
  end
  object ListBox3: TListBox
    Left = 0
    Top = 162
    Width = 257
    Height = 62
    Align = alTop
    ItemHeight = 13
    TabOrder = 5
    ExplicitLeft = -8
    ExplicitTop = 234
  end
  object Panel4: TPanel
    Left = 0
    Top = 224
    Width = 257
    Height = 25
    Align = alTop
    Caption = 'Image'
    TabOrder = 6
    ExplicitTop = 282
  end
  object PanelImage: TPanel
    Left = 0
    Top = 249
    Width = 257
    Height = 105
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 7
    ExplicitLeft = 24
    ExplicitTop = 280
    ExplicitWidth = 185
    ExplicitHeight = 41
    object Image1: TImage
      Left = 0
      Top = 0
      Width = 257
      Height = 105
      Align = alClient
      Enabled = False
      ExplicitTop = 6
    end
  end
end
